services:
  # -- Service 1 : Base de données MySQL --
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      [
        "--default-time-zone=America/Montreal",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./database/init_timezone.sql:/docker-entrypoint-initdb.d/init_timezone.sql
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -- Service 2 : application flask --
  app:
    build: ./web
    container_name: dashboard
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5500:5500"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./web:/web
      - ./database:/web/database

# -- Service 3 : Orchestrateur de prédiction --
  orchestrator:
    build: 
      context: .
      dockerfile: capture/Dockerfile
    container_name: orchestrator_worker
    restart: always
    privileged: true   # ⚠️ obligatoire pour capture réseau
    network_mode: host # ⚠️ accès à l’interface réseau réelle
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      DB_HOST: localhost
      DB_PORT: 3307
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

# -- Service 4 : proxy --
  soar:
    build: 
      context: ./soar
      dockerfile: Dockerfile
    container_name: soar
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    ports:
      - "6000:6000"
    volumes:
      - ./soar/logs:/var/log/soar

  # -- Service 5 : proxy --
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7500:7500"
    depends_on:
      - app
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge


