resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: flask-config
    patch: |-
      data:
        ENV: "production"
        DEBUG: "false"

  - target:
      kind: Deployment
      name: flask-deployment
    patch: |-
      spec:
        replicas: 3
