apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml

  - dashboard-deployment.yaml
  - dashboard-service.yaml

  - orchestrator-daemonset.yaml

  - soar-deployment.yaml
  - soar-service.yaml

  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-init-configmap.yaml

