apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      hostNetwork: true
      containers:
        - name: orchestrator
          image: ml-ddos-orchestrator:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
          envFrom:
            - configMapRef:
                name: orchestrator-config
            - secretRef:
                name: orchestrator-secrets
          env:
            - name: SOAR_URL
              value: "http://127.0.0.1:6000/alert"

