# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: orchestrator
# spec:
#   selector:
#     matchLabels:
#       app: orchestrator
#   template:
#     metadata:
#       labels:
#         app: orchestrator
#     spec:
#       containers:
#         - name: orchestrator
#           image: ml-ddos-orchestrator:latest
#           imagePullPolicy: IfNotPresent
#           securityContext:
#             privileged: true
#             capabilities:
#               add:
#                 - NET_RAW
#                 - NET_ADMIN
#           env:
#             - name: CAPTURE_INTERFACE
#               value: "any"

#             - name: SOAR_URL
#               value: "http://soar:6000/alert"

#             - name: PYTHONUNBUFFERED
#               value: "1"
              
#           envFrom:
#             - secretRef:
#                 name: app-secrets

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      containers:
        - name: orchestrator
          image: ml-ddos-orchestrator:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
          env:
            - name: CAPTURE_INTERFACE
              value: "eth0"   # ‚Üê ETH0 DU NODE
            - name: SOAR_URL
              value: "http://soar:6000/alert"
            - name: PYTHONUNBUFFERED
              value: "1"
          envFrom:
            - secretRef:
                name: app-secrets
