apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # --- Flask ---
  SECRET_KEY: "change-moi-en-prod"
  API_KEY: "supersecretapikey"

  # --- Database ---
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "ddos_detection"
  DB_USER: "bank_user"
  DB_PASSWORD: "ddos_detection_"

  # --- SOAR CORE ---
  SOAR_WEBHOOK_SECRET: "super-long-secret-random-64chars"
  SOAR_MIN_PROBABILITY: "0.70"
  SOAR_WHITELIST_IPS: "127.0.0.,192.168.,10.,172.17.,172.18.,172.19."

  # --- TELEGRAM ---
  TELEGRAM_BOT_TOKEN: "8201418709:AAFtwGkOE7a1AF1BU7P7-yvWQlNHYZr0n3U"
  TELEGRAM_CHAT_ID: "6867100751"
