apiVersion: apps/v1
kind: Deployment
metadata:
  name: soar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soar
  template:
    metadata:
      labels:
        app: soar
    spec:
      containers:
        - name: soar
          image: ml-ddos-soar:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          envFrom:
            - secretRef:
                name: app-secrets
